FROM python:3.13.2-slim

WORKDIR /app

COPY src/ /app/src/
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 31337

WORKDIR /app/src

CMD ["uvicorn", "main_api:app", "--host", "0.0.0.0", "--port", "31337"]
