# fly.toml app configuration file generated for webscreencap-celery-worker on 2025-01-26T00:18:08-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'webscreencap-celery-worker'
primary_region = 'iad'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
