# fly.toml app configuration file generated for webscreencap on 2025-01-25T23:07:38-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'webscreencap'
primary_region = 'eze'

[build]

[http_service]
  internal_port = 31337
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
